import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import TestimonialSwiper from '@/components/testimonialSwiper/testimonialSwiper.component';
import Modal from '@/components/modal/modal.component';
import { useState } from 'react';
import Drawer from '@/components/drawer/drawer.component';

const testimonials = [
  {
    id: 1,
    customerImg: 'https://source.unsplash.com/100x100/?portrait',
    productName: 'Product A',
    productImg: 'https://source.unsplash.com/300x200/?product',
    testimonialText:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lobortis libero nec orci venenatis, sed facilisis turpis suscipit.',
    linkToProduct: 'https://example.com/product-a',
    customerName: 'John Doe',
  },
  {
    id: 2,
    customerImg: 'https://source.unsplash.com/100x100/?person',
    productName: 'Product B',
    productImg: 'https://source.unsplash.com/300x200/?product',
    testimonialText:
      'Pellentesque et lacus pretium, maximus lectus vel, dignissim libero. Sed lobortis libero nec orci venenatis, sed facilisis turpis suscipit.',
    linkToProduct: 'https://example.com/product-b',
    customerName: 'Jane Smith',
  },
  {
    id: 3,
    customerImg: 'https://source.unsplash.com/100x100/?people',
    productName: 'Product C',
    productImg: 'https://source.unsplash.com/300x200/?product',
    testimonialText:
      'Fusce laoreet, ante eu sollicitudin facilisis, nisi augue interdum eros, non blandit orci sapien id mi. Sed lobortis libero nec orci venenatis, sed facilisis turpis suscipit.',
    linkToProduct: 'https://example.com/product-c',
    customerName: 'Bob Johnson',
  },
];

export default function Home() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const handleDrawerOpen = () => {
    setIsDrawerOpen(true);
  };

  const handleDrawerClose = () => {
    setIsDrawerOpen(false);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleDrawerOpen}>Open Drawer</button>
        <Drawer isOpen={isDrawerOpen} onClose={handleDrawerClose}>
          <h2>Drawer Content</h2>
          <p>Some content goes here.</p>
        </Drawer>
      </main>
    </>
  );
}
