import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import TestimonialSwiper from '@/components/testimonialSwiper/testimonialSwiper.component';
import Modal from '@/components/modal/modal.component';
import { useState } from 'react';
import Layout from '@/components/layout/layout.component';
import Hero from '@/components/hero/hero.component';
import ContactForm from '@/components/contactForm/contactForm.componet';

const testimonials = [
  {
    id: 1,
    customerImg:
      'https://media.licdn.com/dms/image/C5603AQEvmOCsCW-gSg/profile-displayphoto-shrink_800_800/0/1658973866644?e=1689206400&v=beta&t=50UaDaCNyioxjpbTD2ATo0P7rJ5d0dsoUBOeEdomLuU',

    testimonialText:
      'Thomas Krogh has been a fantastic pupil for studying web development. He has shown tremendous fortitude when it comes to facing challenges and has a great attitude towards learning. He is a great team player and has a great sense of humor. I would recommend Thomas to any company that is looking for a web developer.',
    customerName: 'Frankie Krogh',
  },
];

export default function Home() {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleDrawerOpen = () => {
    setIsDrawerOpen(true);
  };

  const handleDrawerClose = () => {
    setIsDrawerOpen(false);
  };

  const handleModalOpen = () => {
    setIsModalOpen(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal
        title="Notice"
        text="Our website uses cookies to improve your browsing experience and to personalize content and ads. By continuing to browse the site, you agree to our use of cookies. To learn more about our cookie policy and to manage your cookie preferences, please review our Privacy Policy."
        buttonText="Got it"
        onClose={() => {
          localStorage.setItem('cookiesAccepted', 'true');
        }}
        setIsOpen={setIsModalOpen}
        isOpen={isModalOpen}
      />

      <Layout>
        <div className={styles.main}>
          <Hero />
          <TestimonialSwiper testimonials={testimonials} />
          <ContactForm />
        </div>
      </Layout>
    </>
  );
}
